version: "3.8"
services:
  langoustine-server:
    build: .
    image: langoustine-server
    environment:
      - PORT=8000
      - DB_CONN_URL=mongodb://langoustine-db:27017
      - DB_NAME=langoustine
    ports:
      - "8000:8000"
    depends_on:
      - langoustine-db
    volumes:
      - .:/src
    networks:
      - langoustine-network
  langoustine-db:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - langoustine-network
volumes:
  dbdata6:
networks:
  langoustine-network:
    driver: bridge
